### PR TITLE
Exported geddit.vote (which is now geddit.Vote)

### PR DESCRIPTION
**Pull request by TheGreatPanda**
I exported geddit.vote. The old geddit.vote created interesting problems:
```Go
// This used to be impossible:
inp := getInputFromSomewhere()
var vote geddit.vote
switch inp {
case "up":
    vote = geddit.UpVote
case "down":
    vote = geddit.DownVote
    // Etc
}
```

### CODE REVIEW

**Comment by jzelinskie** [comment]
I hadn't considered this scenario. You should probably set some git credentials, the commit info is set to "Your Name".

**Comment by TheGreatPanda** [comment]
Sorry, I'm quite new to the whole git/github workflow :). So, now that I've set my credentials, what should I do?

**Comment by jzelinskie** [comment]
No problem! Changing the commit to contain your new author credentials is a little tricky for someone new to git. You're best off simply running `git reset --hard 9a23e13` and making the change and committing it again with your new credentials set. Then you have to `git push -f` to overwrite the branch.

**Comment by jzelinskie** [comment]
Woah, didn't know github automatically closed PRs without any new commits.

**Comment by TheGreatPanda** [comment]
I'm going to submit a pull request now. Thanks so much for your help :100:.

**Pull request closed without merging**
